nyaruka/courier

- backends/rapidpro/backend.go
- cmd/courier/main.go
- config/courier.go
- msg.go
- queue/queue.go
- queue/queue_test.go
- test.go
This sadly complicates our lua/redis queuing even more, but it is the only way I've figured out how to satisfy both max transactions per second on channels as well as fair queueing across channels, having priorities AND spacing out messages on the same contact by a set amount of time. (currently that is at least 5 seconds [could be more depending on what is in the queue but shouldn't be if we set priorities smartly])
Typical push and pop are still in the .15ms range so performance still seems ok.
> Add support for multiple messages per contact

- channel.go
- config/courier.go
- librato/librato.go
- sender.go
- server.go
I looked at a bunch of libraries to do this but they were all sucky in one way or another. Boo.
> Add librato logging

- backends/rapidpro/channel.go
- channel.go
- config/courier.go
- config/test.go
- handlers/dmark/dmark.go
- handlers/dmark/dmark_test.go
- handlers/kannel/kannel.go
- handlers/kannel/kannel_test.go
- handlers/test.go
- handlers/twilio/twilio.go
- handlers/twilio/twilio_test.go
- server.go
- test.go
Removed `Scheme` as a config as:
1) I'm fine forcing https for callbacks (SSL everywhere!)
2) and I thought it was a bit confusing as a config option as it felt like it was implying that we were serving via https (when really we are listening on a high port and SSL is handled upstream)
> Use callback domain when registering callbacks for sent messages

- handlers/mtarget/mtarget.go
- handlers/mtarget/mtarget_test.go
- log.go
- responses.go
Allow sending unicode, deal with multiparts that come in separately.
> further tweaks to mtarget

- handlers/base.go
- handlers/external/external.go
- handlers/jiochat/jiochat.go
- handlers/kannel/kannel.go
- handlers/nexmo/nexmo.go
- handlers/shaqodoon/shaqodoon.go
- handlers/smscentral/smscentral.go
- handlers/smscentral/smscentral_test.go
- handlers/yo/yo.go
Removed the QueryParams function as the Form version takes care of both URL parameters and POST parameters (in the case of POST).
> tweaks to smscentral before shipping, simplify form parsing

- handlers/highconnection/highconnection.go
- handlers/highconnection/highconnection_test.go
> Highconnection handlers

- handlers/facebook/facebook.go
- handlers/facebook/facebook_test.go
This deals with the case @ycleptkellan  brought up, namely we really have three types of events we have to deal with:
1) "Get Started" postbacks that come in without an referral, this should trigger a `NewConversation` event
2) "Get Started" postbacks that come in with a referral, say if someone clicks a m.me link then "Get Started".. this should be a "Referral" event
3) A straight Referral, these are unchanged and create  "Referral" event
We are basically changing 2 to be a Referral event while before it was a NewConversation
> correctly use referral for get started off an m.me link

- backends/rapidpro/backend_test.go
- backends/rapidpro/contact.go
- backends/rapidpro/urn.go
replaces #137, @johncordeiro I think this is a bit more efficient approach, as it doesn't require an extra query on every message hit. Give it a look.
> check for auth changes when making sure URN is default

- backends/rapidpro/backend.go
- backends/rapidpro/backend_test.go
- backends/rapidpro/channel.go
- backends/rapidpro/testdata.sql
- channel.go
- handlers/external/external.go
- handlers/external/external_test.go
- test.go
Two little issues:
1) if we fail to grab a channel when popping a message off to send, we weren't marking that task as complete, this was horking our status dashboard for how many workers we had assigned to that channel
2) we weren't dealing with int config values properly so were ignoring max length for external channels. Added a `GetIntConfig` that makes that easier for callers.
> Fix # of workers when there is error, fix int config reading

- backends/rapidpro/backend.go
- backends/rapidpro/backend_test.go
- backends/rapidpro/msg.go
two changes that are for the better:
- our key in our seen messages map is now channel/urn instead of channel/urn/text. the previous behavior meant that it was possible with very fast interactions to have more than one thing in each map for any channel/urn which increased the likelyhood of collisions
- when we mark a message as sent (ie we just sent something out) we clear the seen incoming messages for a channel/urn. that should keep fast interactions with the same response from being caught
> clear dedupes on outgoing messages

- handlers/novo/novo.go
- handlers/novo/novo_test.go
This PR is linked to [rapidpro](https://github.com/rapidpro/rapidpro/pull/804) which expect to receive the same secret key as Authorization header in received messages.
> Add authorization requirement on Novo Channel

- backend.go
- backends/rapidpro/backend.go
- backends/rapidpro/task.go
- handlers/test.go
- handlers/twilio/twilio.go
- handlers/yo/yo.go
- test.go
We had two ways to do it before, a custom stop event and a channel event with type stop, this just unifies the two.
> always report stops as stop channel events

- handlers/jiochat/jiochat.go
be flexible/ignore when the key for nickname is not present
> Ignore error for Jiochat user name lookup

- handlers/zenvia/zenvia.go
Recently Zenvia changed your API endpoint.
Zenvia doc: https://zenviasmsenus.docs.apiary.io/#reference/api-services/sending-a-single-sms/sending-a-single-sms
New endpoint: https://api-rest.zenvia.com/services
Now only HTTPS (TLS v1.2) protocol is allowed.
> Changed Zenvia API endpoint

- backend.go
- backends/rapidpro/backend.go
- backends/rapidpro/backend_test.go
- backends/rapidpro/msg.go
- codecov.yml
- handlers/test.go
- handlers/whatsapp/whatsapp.go
- handlers/whatsapp/whatsapp_test.go
- test.go
We've had a few cases where the WA business API sends us the same message more than once.
The flows in Rapidpro responds to both messages which is not a desirable outcome for us.
This PR will deduplicate messages based on the external ID on the WA channel.
> Deduplicate WA messages on external ID

- handlers/whatsapp/whatsapp.go
- handlers/whatsapp/whatsapp_test.go
Version 2.23.4 of the WhatsApp Business API allows for sending of mp4 videos. This PR adds support for that.
> Add video support for WhatsApp

- backends/rapidpro/channel.go
- channel.go
- cmd/courier/main.go
- config.go
- handlers/test.go
- handlers/twiml/twiml.go
- handlers/twiml/twiml_test.go
- test.go
https://signalwire.com/
Mostly the same API as Twilio except they don't sign.
Renamed `twilio` handler to `twiml` since that's more accurate now.
Also removed global 'ignore_delivery_reports' setting which was only used by Resist. That's now a channel config. 
@chris-erickson, I set `ignore_dlrs` to `true` on the config for the main ResistBot Twilio channel so this doesn't change anything for you. (that global config option was only for resist)
> Add SignalWire handler

- backends/rapidpro/channel.go
- channel.go
- handlers/twiml/twiml.go
- handlers/twiml/twiml_test.go
- test.go
Not positive this is the right approach, we may want to add a `WAT` type for "WhatsApp Twilio" but this lets us test this out with a customer to start, we can switch them over once we add a new channel type. (also want to limit changes due to v5 push)
We have a customer with a Twiliio WA number so this addresses that.
> add whatsapp scheme to twiml channels

- handlers/external/external.go
- handlers/external/external_test.go
This is a hotfix related to PR #275 that replace the `{{quick_replies}}` variable in all message part requests. The current implementation keeps the "{{quick_replies}}" string in send URL/body of parts before the last one, breaking the request format. Therefore, replacing that variable by it's list zero value according send method and content type.
> Fix quick replies variable replacement on external channel long msg

- backends/rapidpro/backend.go
- backends/rapidpro/backend_test.go
- backends/rapidpro/status.go
- backends/rapidpro/urn.go
- handlers/whatsapp/whatsapp.go
- handlers/whatsapp/whatsapp_test.go
- status.go
- test.go
PR https://github.com/nyaruka/courier/pull/286 makes contact verification by `POST /v1/contacts`, validating the phone number before a new retry to `POST /v1/messages`, when the first try fails with error `"unknown contact"`. Response body format for contact verification:
```json
{
"contacts": [{"input": "16315551000", "status": "valid", "wa_id": "16315551000"}]
}
```
This PR adjusts the retry request to use the `"wa_id"` returned from contact verification instead of the URN, because we may have inconsistencies in the format of phone numbers in some country when they are registered via API or manually.
In our case, in Brazil, a 9th digit has been incorporated into phone numbers in recent years, but not in WhatsApp, there are regions with 8-digit phone numbers while they are registered in …
> Retry WhatsApp messaging after contact verification with returned WhatsApp ID

- handlers/playmobile/playmobile.go
- handlers/playmobile/playmobile_test.go
The Play Mobile service places a prefix (from a list of possible prefixes) on user messages, for free accounts.
This PR is for clearing those messages when the channel has the `incoming_prefixes` config set - the type is string array and the check is case insensitive - , so user responses can be handled normally.
> Remove incoming message prefix for Play Mobile free accounts

- backends/rapidpro/msg.go
- handlers/external/external.go
- msg.go
- test.go
Mailroom passes the session status to courier. We would like to pass that on in the external API URL call.
Relates to https://github.com/rapidpro/rapidpro/issues/1298
> Add session status from mailroom to MT message sent to external channel API CGI parameters

- handlers/whatsapp/whatsapp.go
- handlers/whatsapp/whatsapp_test.go
This allows RapidPro to handle quickreply responses / button messages, by interpreting the button text as the message text.
More details in https://github.com/rapidpro/rapidpro/issues/1430
> Add handling for whatsapp quickreply responses

- handlers/bongolive/bongolive.go
BongoLive now Beem Africa have a self signed certificate and that is failing to validate.
I tried to clarify that to team so that they can fix that but if they do not we can ignore the verification so messages are sent.
> Do not verify the SSL certificate for Bongo Live

- backend.go
- backends/rapidpro/backend.go
- backends/rapidpro/backend_test.go
- backends/rapidpro/msg.go
- msg.go
- sender.go
- test.go
The sender orchestration doesn't have a super nice unit test (it's tested as an integration test with all the various handlers) so need to figure out a better testing strategy for this
> add is_resend to Msg payload to allow for resending messages manually

- handlers/whatsapp/whatsapp.go
- handlers/whatsapp/whatsapp_test.go
- utils/misc.go
- utils/misc_test.go
As said in #353 , I've tested locally and this is the difference:
From:
To:
> Add Filename

- backends/rapidpro/backend.go
Update to latest gocommon adds context param to Storage.Test(..)
Noticed pushing to staging we got an error saying "S3 storage not available" but it was working fine https://sentry.io/organizations/nyaruka/issues/2525368566/?project=181813&query=is%3Aunresolved
> Give S3 storage test new context

- go.mod
- handlers/facebookapp/facebookapp_test.go
We do get the body already escaped and that's what we calculate against so things work fine with unicode. this just tests that we aren't stripping leading `a`s from the sig.
> add test for fb sigs

- handlers/telegram/keyboard.go
- handlers/telegram/keyboard_test.go
- handlers/telegram/telegram.go
- handlers/telegram/telegram_test.go
- utils/misc.go
- utils/misc_test.go
Does #373 for Telegram. Adds some generic buttony layout stuff we should be able to re-use for other channels that support keyboard things
> Smarter organization of quick replies into rows and columns for telegram keyboards

- handlers/africastalking/africastalking.go
- handlers/africastalking/africastalking_test.go
Add support for the 'Expired' status from Africa's Talking which seems
to be thrown but isn't handled. Courier currently throws the following
error when it encounters this status:
time="2021-11-10T10:29:10+03:00" level=info msg="request errored"
channel_uuid=<UUID> elapsed_ms=0.109525 error="unknown status
'Expired', must be one of 'Success','Sent', 'Buffered','Rejected'
or 'Failed'" url=/c/at/<UUID>/status
Mark messages that have this status as failed as it doesn't appear
messages that have this status get delivered to users.
Signed-off-by: Jason Rogena <jason@rogena.me>
> Adds the Africa's Talking 'Expired' Status in Its Handler

- backend.go
- backends/rapidpro/backend.go
- backends/rapidpro/backend_test.go
- sender.go
- test.go
Once mailroom starts doing it https://github.com/nyaruka/mailroom/pull/537
> Remove loop detection

- backends/rapidpro/contact.go
- backends/rapidpro/msg.go
- backends/rapidpro/urn.go
So we can see where the `context canceled` errors are coming from
> Do more error wrapping when creating contacts and URNs

- backends/rapidpro/status.go
Struggling to find a good way to test this.. the status update was successful, but then it was failing to get the returned id, so so it would call the error handler of the status committer... which would try to spool the update, but that would also fail because the spool directory doesn't exist, but all that is swallowed by the tests.
> Fix bulk status updates

- handlers/whatsapp/whatsapp.go
Added languages:
- Georgian
- Kinyarwanda
[Language list](https://developers.facebook.com/docs/whatsapp/api/messages/message-templates/#supported-languages)
> Language support missing from WhatsApp templates

- handlers/whatsapp/whatsapp.go
- handlers/whatsapp/whatsapp_test.go
fixing bug with attachment filename in whatsap handler, as discussed here: https://github.com/nyaruka/courier/issues/383
> fix whatsapp uploaded attachment file name

- handlers/facebookapp/facebookapp.go
- handlers/facebookapp/facebookapp_test.go
Fix for bug discussed in issue #418
> Fix metadata fetching for new Facebook contacts

- handlers/twiml/twiml.go
Fixes https://sentry.io/organizations/nyaruka/issues/3120037472/?project=205713&referrer=alert_email
> Fix handling stops via status callbacks on Twilio

- channel_log.go
- go.mod
- go.sum
- handlers/whatsapp/whatsapp.go
The added [library](https://github.com/gabriel-vasile/mimetype) has more type support than the currently used library, including `.xlsx` files that were previously being shipped as `.zip` due to lack of support from the current library.
> Add library with greater support for detection of mime types in Whatsapp

- handlers/whatsapp/whatsapp.go
- handlers/whatsapp/whatsapp_test.go
Support to include a URL preview in messages with links sent on Whatsapp. Add `"preview_url": true` to the message body as indicated in the [documentation](https://developers.facebook.com/docs/whatsapp/api/messages/text#urls).
> Support for viewing sent links in Whatsapp messages

- channel_log.go
This is a quick fix allow JSON content in channel logs currently being omitted.
The proper refactor is to address https://github.com/nyaruka/courier/issues/435
> Quick fix to allow JSON content to not be omitted in logs

- handlers/whatsapp/whatsapp.go
- handlers/whatsapp/whatsapp_test.go
Audio attachment can not be sent with a caption so we need to send the text after
> Make sure text are sent after audio attachments for WA channels

- handlers/facebookapp/facebookapp.go
- handlers/facebookapp/facebookapp_test.go
Support to include a URL preview in messages with links sent in Whatsapp. Add `"preview_url": true` to the Message Text Object as indicated in the [documentation](https://developers.facebook.com/docs/whatsapp/cloud-api/reference/messages#:~:text=of%20type%20video.-,Text%20Object,-Name).
> Add link preview support in WAC

- handlers/facebookapp/facebookapp.go
- handlers/facebookapp/facebookapp_test.go
- handlers/facebookapp/testdata/wac/buttonReplyWAC.json
- handlers/facebookapp/testdata/wac/listReplyWAC.json
The quick replies were not being identified in the receive, causing problems during the exchange of messages. I identified that they are part of this `Interactive` type that also has list replies, I took advantage and added these as well.
> Fix receiving quick replies and list replies in WAC

- backends/rapidpro/msg.go
- handlers/facebookapp/facebookapp.go
- handlers/facebookapp/facebookapp_test.go
- handlers/test.go
Receiving attachments is not working properly. First, the token used to fetch the media url, channel auth_token, does not exist as WAC channels do not have this token in the channel settings. The token that must be used is the `whatsapp_admin_system_user_token` and in addition, for the media to be downloaded, it is necessary to use the same token.
> Fix receiving attachments in WAC

- handlers/facebookapp/facebookapp.go
Cloud API updated one of the attributes coming in the payload of webhooks for status update, the `expiration_timestamp` which is currently not used at all in the WAC handler, is coming with the type `string` in some cases, causing divergence with `int64 ` that it has in the `moPayload` struct. As it is not used, it is best to remove it.
> Remove expiration_timestamp from moPayload in WAC

- attachments.go
- attachments_test.go
- backends/rapidpro/backend.go
- backends/rapidpro/backend_test.go
- backends/rapidpro/msg.go
- backends/rapidpro/task.go
- server.go
- server_test.go
It's convenient to store attachments as a single string but that only needs to be a last minute thing when writing to the db
> Rework attachment fetching to keep URL and content type separate

- attachments.go
- handler.go
- handlers/facebookapp/facebookapp.go
- handlers/facebookapp/facebookapp_test.go
- handlers/jiochat/jiochat.go
- handlers/jiochat/jiochat_test.go
- handlers/line/line.go
- handlers/line/line_test.go
- handlers/rocketchat/rocketchat.go
- handlers/wechat/wechat.go
- handlers/wechat/wechat_test.go
- handlers/whatsapp/whatsapp.go
- handlers/whatsapp/whatsapp_test.go
Instead of relying on scheduled task in RP
Also fixes channel log redaction for these channel types.
> 🔐 Fetch access token for JioChat and WeChat channels as needed

- attachments.go
- attachments_test.go
https://sentry.io/organizations/nyaruka/issues/3708720249/events/d835aac10c7347b5a4befeb915d1105b/?project=205713
> Allow empty attachments, e.g. a txt file

- attachments.go
- attachments_test.go
- channel_log.go
I left this out initially because we're in theory moving toward not saving channel logs with msg ids.. but until we get there.. it's useful to have
> Allow msg id to be passed to fetch attachment requests and saved on the channel log

- attachments.go
- attachments_test.go
- server_test.go
- test/backend.go
We still see this happening for really big attachments on 360dialog channels
> Fetch attachments endpoint should return connection timeouts as unavailable attachments

- backends/rapidpro/backend.go
- backends/rapidpro/backend_test.go
- backends/rapidpro/msg.go
Trying to cleanup what mailroom sends to courier so we're not wasting redis bytes
> Remove JSON tags for msg fields not used in sending

- backends/rapidpro/backend.go
- backends/rapidpro/backend_test.go
- backends/rapidpro/status.go
This resolves external ids to database ids in the batcher using a database lookup - I think it makes sense to optimize that by stuffing external ids in redis, but also it's not going to be much of a performance hit to not do that for now since the lookup is in batches - and I've checked it's just an index scan on `msgs_by_external_id`.
Of course the other reason to put external ids in redis is to avoid the race condition of trying to do a status update by external id before the status update that sets the external id. This won't fix that but it should make it less likely because previously the status update to write the external id was being done async (always a delay) but a subsequent update using that external id would by sync (no delay)... now they're both queued, both async, both with …
> Rework writing status updates so that updates by external id also use the batcher

- backends/rapidpro/backend_test.go
- backends/rapidpro/msg.go
- handlers/firebase/firebase_test.go
- handlers/highconnection/highconnection.go
- handlers/test.go
- msg.go
- responses_test.go
- test/backend.go
- test/msg.go
Methods only used for testing only need to be on `MockMsg`
> Simpler `Msg` interface

- backends/rapidpro/backend_test.go
- backends/rapidpro/channel_event.go
- backends/rapidpro/schema.sql
- backends/rapidpro/testdata.sql
- channel_event.go
- handlers/facebook_legacy/handler.go
- handlers/facebook_legacy/handler_test.go
- handlers/meta/facebook_test.go
- handlers/meta/handlers.go
- handlers/meta/instagram_test.go
- handlers/test.go
- responses.go
- test/channel_event.go
* RP backend now extracts optin id from extra and saves as actual id in the database
* Change `extra` fields on optin/optout events to be more consistent with other FB/IG events
* Enforce `extra` being map[string]string as this avoids problems if an event is spooled to JSON and reloaded (ints become floats)
> Channel Event OptIn ID

- handlers/facebook_legacy/handler.go
- handlers/hormuud/handler.go
- handlers/messagebird/handler.go
- handlers/twiml/handlers.go
- handlers/whatsapp_legacy/handler.go
> Replace logrus with slog in handlers packages

- handlers/whatsapp_legacy/handler.go
- handlers/whatsapp_legacy/handler_test.go
HSM templates were used in old docker API clients that are not longer supported, now we use template
And this is to prepare to support more complex templates components
> Remove support for HSM template support

- backends/rapidpro/msg.go
- handlers/tembachat/handler.go
- handlers/tembachat/handler_test.go
- handlers/test.go
- msg.go
- test/msg.go
Just using user id worked with temba-chat because it can look up users, but we also want the new mailgun handler to know about who sent a message.. without courier having to look up users from the database.
> Add user email and name to queued messages

- handler.go
- handler_test.go
- handlers/africastalking/handler.go
- handlers/africastalking/handler_test.go
- handlers/arabiacell/handler.go
- handlers/arabiacell/handler_test.go
- handlers/tembachat/handler.go
- handlers/tembachat/handler_test.go
- handlers/test.go
- sender.go
- test/handler.go
See #653 
* Allows handlers to implement one of two interfaces that differ by send method to allow handlers to be rewritten piece meal.
* New `Send` contract takes away need for handlers creating `StatusUpdate` objects - they return different error singletons and then sender determines whether message should be be retried.
* Or for things like db errors.. they can return a regular `error` and that is treated as a logged, retryable internal error
* Have send errors become channel log errors to avoid duplicating those.
> Refactor sending to do less retrying and let handlers be dumber

- handlers/africastalking/handler_test.go
- handlers/arabiacell/handler_test.go
- handlers/bandwidth/handler_test.go
- handlers/bongolive/handler_test.go
- handlers/burstsms/handler_test.go
- handlers/clickatell/handler_test.go
- handlers/clickmobile/handler_test.go
- handlers/clicksend/handler_test.go
- handlers/dialog360/handler_test.go
- handlers/infobip/handler_test.go
- handlers/test.go
- handlers/twiml/handlers_test.go
- handlers/viber/handler_test.go
> Remove deprecated test fields

- handlers/dialog360/handler_test.go
- handlers/meta/whataspp_test.go
- handlers/meta/whatsapp/templates.go
- handlers/meta/whatsapp/templates_test.go
Requires https://github.com/nyaruka/goflow/pull/1232
> Use templating component type

- backends/rapidpro/msg.go
- handlers/dialog360/handler.go
- handlers/dialog360/handler_test.go
- handlers/meta/handlers.go
- handlers/meta/whataspp_test.go
- handlers/meta/whatsapp/templates.go
- handlers/meta/whatsapp/templates_test.go
- handlers/test.go
- handlers/whatsapp_legacy/handler.go
- handlers/whatsapp_legacy/handler_test.go
- msg.go
- test/msg.go
Requires https://github.com/nyaruka/mailroom/pull/233
> Read templating from new `templating` msg field instead of `metadata`

- backends/rapidpro/backend_test.go
- backends/rapidpro/status.go
- handlers/kaleyra/handler.go
- handlers/kaleyra/handler_test.go
- handlers/meta/whatsapp/api.go
- handlers/twiml/handlers.go
- handlers/twiml/handlers_test.go
- handlers/whatsapp_legacy/handler.go
- handlers/zenvia/handlers.go
- status.go
Requires https://github.com/nyaruka/rapidpro/pull/5205
> Add support for read msg status

- backends/rapidpro/backend.go
- backends/rapidpro/contact.go
- backends/rapidpro/msg.go
- backends/rapidpro/status.go
- backends/rapidpro/urn.go
- go.mod
- go.sum
- handlers/facebook_legacy/handler.go
- handlers/jiochat/handler.go
- handlers/kaleyra/handler.go
- handlers/line/handler.go
- handlers/media.go
- handlers/meta/handlers.go
- handlers/shaqodoon/handler.go
- handlers/slack/handler.go
- handlers/telegram/handler.go
- handlers/viber/handler.go
- handlers/vk/handler.go
- handlers/wechat/handler.go
- handlers/whatsapp_legacy/handler.go
- handlers/yo/handler.go
- sender.go
- server.go
- test/backend.go
- test/handler.go
contains https://github.com/nyaruka/courier/pull/747
> Std Error part 2

- handlers/dialog360/handler.go
- handlers/dialog360/handler_test.go
- handlers/meta/handlers.go
- handlers/meta/whataspp_test.go
The engine now include attachment for media templates so we use template when present
No change for legacy WA as that do not support other components except body
> Adjust WA template to be send if present even when we have attachments

- channel_log.go
- server_test.go
We're currently writing channel log objects to the database that we shouldn't be.. channel logs are considered `attached` if they are referenced by a message, therefore don't need to be written to the database because they will be accessed via the message that has the UUID of the log so we can find it in S3.
> Fix unnecessarily writing send channel logs to the database

- backends/rapidpro/backend.go
Cuz now we're also using it for testing S3 bucket access below.. previously those S3 calls didn't take a context
> Fix context used during backend startup

- channel_log.go
- channel_log_test.go
- server_test.go
We currently put logs into S3 "subdirectories" using the first 4 chars of the UUID.. which will now be the same for all logs.. can't easily change that because RP infers it. I think it's only liable to be a problem if trying to browse logs for a big channel on the AWS console.
> Use ordered v7 UUIDs for channel logs

- handlers/meta/handlers.go
- handlers/meta/whataspp_test.go
This reverts commit 2deefc43f47d9452854a111ab01420b62993dcc2.
> Revert "Fail messages when we hit contact pair limit"

- backends/rapidpro/stats.go
- backends/rapidpro/stats_test.go
… because apparently we don't need them
> Remove previously added aggregated versions of channel type specific metrics

- backends/rapidpro/backend.go
- backends/rapidpro/backend_test.go
- backends/rapidpro/msg.go
- backends/rapidpro/schema.sql
- backends/rapidpro/timeouts.go
- handlers/external/handler.go
- handlers/firebase/handler.go
- msg.go
- test/msg.go
Shouldn't deploy until all queued messages were queued by mailroom v10.1.21+
> Start using new session field on queued messages

- backends/rapidpro/backend.go
- backends/rapidpro/backend_test.go
- backends/rapidpro/msg.go
- backends/rapidpro/timeouts.go
Requires https://github.com/nyaruka/mailroom/pull/434
> Simplify contact fire inserted for timeouts

- handlers/bandwidth/handler.go
- handlers/bandwidth/handler_test.go
Renamed the config key for BW messaging app ID
> Rename config for BW messaging application ID
