- backend.go
- backends/rapidpro/backend.go
- backends/rapidpro/backend_test.go
- backends/rapidpro/msg.go
- sender.go
- test.go
Fixes https://github.com/nyaruka/courier/issues/21
> Add failsafe against duplicate sending

- backends/rapidpro/msg.go
- backends/rapidpro/schema.sql
- backends/rapidpro/testdata.sql
> Stop using msgs_msg.has_template_error which is now nullable 

- handlers/infobip/infobip.go
- handlers/infobip/infobip_test.go
Fixes https://sentry.io/nyaruka/rapidpro-courier/issues/407474217/
> Message send errors should be logged to channel logs

- backends/rapidpro/backend.go
Send authentication command if the Redis host requires a password to connect
> Redis auth

- Gopkg.lock
- backend.go
- backends/rapidpro/backend.go
- backends/rapidpro/backend_test.go
- backends/rapidpro/channel_event.go
- backends/rapidpro/contact.go
- backends/rapidpro/msg.go
- backends/rapidpro/urn.go
- cmd/courier/main.go
- contact.go
- handlers/firebase/firebase.go
- handlers/firebase/firebase_test.go
- handlers/test.go
- msg.go
- test.go
- vendor/github.com/go-chi/chi/middleware/logger.go
- vendor/github.com/go-chi/chi/middleware/terminal.go
- vendor/github.com/go-chi/chi/middleware/wrap_writer.go
- vendor/github.com/nyaruka/gocommon/urns/urns.go
Slightly more complicated as we need to introduce the idea of contact creation as well as auth on URN.
> Implement firebase

- cmd/courier/main.go
- handlers/junebug/junebug.go
- handlers/junebug/junebug_test.go
- handlers/test.go
- responses.go
No USSD for now support as that is still an unknown going forward.
> Junebug handler

- handlers/vumi/vumi.go
> Remove Vumi

- config.go
- server.go
> Added an Address option to bind to a specific network interface address

- handlers/infobip/infobip.go
- handlers/infobip/infobip_test.go
see: https://dev.infobip.com/docs/transliteration
> add optional transliteration parameter for MT messages

- handlers/africastalking/africastalking.go
- handlers/africastalking/africastalking_test.go
> 📅 AT date like 2006-01-02 15:04:05, without T nor Z

- handlers/whatsapp/whatsapp.go
First step so we can have proper logs that will better explain why we do not get the expected ID,
Then we can fix that
> 🎈 Better channel logs support for WA channels

- handlers/external/external.go
- handlers/external/external_test.go
Don't think this is the source of the issue but needed fixing.
> fix soap panics

- go.sum
- handlers/bongolive/bongolive.go
- handlers/bongolive/bongolive_test.go
TO be merged after #204 and #202
> Bl channel

- backends/rapidpro/msg.go
- handlers/test.go
- handlers/whatsapp/whatsapp.go
- handlers/whatsapp/whatsapp_test.go
- msg.go
- test.go
Depends on pending rapidpro, goflow, editor and mailroom work.
> implement sending whatsapp templates

- handlers/external/external.go
- handlers/external/external_test.go
This will allow external channels to be a bit more flexible. Don't plan on adding UI for this just yet.
> allow configuring custom mo fields

- backends/rapidpro/backend_test.go
- backends/rapidpro/channel.go
- backends/rapidpro/schema.sql
- backends/rapidpro/task.go
This will trigger a new major release.
> ignores flow server enabled attribute on orgs

- backends/rapidpro/contact.go
- backends/rapidpro/schema.sql
- backends/rapidpro/testdata.sql
We'll have to bump our major version number for this as it will break others.
> stop looking / writing is_test

- handlers/viber/viber.go
- handlers/viber/viber_test.go
filling our sentry logs currently
> ignore viber dlrs as they are sent for both in and out

- backend.go
- backends/rapidpro/backend.go
- backends/rapidpro/backend_test.go
- sender.go
- test.go
This basically means that any time a contact gets the same flow message more than 20 times in a 5 minute window we will fail it. I *think* that's reasonable.
> Check whether outgoing message is in a loop before sending

- handlers/whatsapp/whatsapp.go
- handlers/whatsapp/whatsapp_test.go
This is a PR for this issue.
https://github.com/nyaruka/courier/issues/255
> Whatsapp contact name

- handlers/twiml/twiml.go
- handlers/twiml/twiml_test.go
fixes https://github.com/nyaruka/courier/issues/270
> Added read status for whatsapp twilio support

- .github/workflows/ci.yml
Just making same tweak from mailroom whilst I remember
> Allow non-master releases

- go.mod
- go.sum
- handlers/shaqodoon/shaqodoon.go
- handlers/shaqodoon/shaqodoon_test.go
Also updated phonenumbers to latest.
I thought about putting this in `StrictTelForCountry` but that felt a too much like a global hack.
> Fix shaqodoon escaping

- handlers/whatsapp/whatsapp.go
- handlers/whatsapp/whatsapp_test.go
This is the piece of code to support the new channel type for WhatsApp channels: 360Dialog. I've started [an issue in the RapidPro repository](https://github.com/rapidpro/rapidpro/issues/1278) and also [sent the PR](https://github.com/rapidpro/rapidpro/pull/1280) for the channel type in the backend.
> New WhatsApp BSP channel: 360dialog

- handlers/whatsapp/whatsapp.go
- handlers/whatsapp/whatsapp_test.go
also clean up duping in tests.
> add textit whatsapp channel type

- handlers/twiml/twiml.go
- handlers/twiml/twiml_test.go
Fixes https://sentry.io/organizations/nyaruka/issues/2324763865/?project=205713
Assuming that request is meant for that endpoint?
> Handle whatsapp URNs sent to Twiml handler without prefix

- backends/rapidpro/contact.go
- backends/rapidpro/schema.sql
- backends/rapidpro/testdata.sql
Requires https://github.com/nyaruka/rapidpro/pull/3461 by deployed first
> 🧛 Populate ticket_count when creating new contacts

- handlers/vk/keyboard.go
- handlers/vk/keyboard_test.go
- handlers/vk/vk.go
- handlers/vk/vk_test.go
This PR is about supporting quick replies to VK handler. VK treats quick replies as keyboard, [here](https://vk.com/dev.php?f=4.%20Bot%20keyboards&method=bots_docs_3) we can see in more detail about keyboards.
> Quick Replies for VK

- handlers/whatsapp/whatsapp.go
Fix for bug discussed in issue #403.
> Fix Gujarati language code on WhatsApp templates

- handlers/whatsapp/whatsapp.go
PR on Rapidpro https://github.com/nyaruka/rapidpro/pull/3677
> Support to Kyrgyzstan language on WhatsApp Templates

- goreleaser.yml
Ensure there are arm64 binaries in the release assets
> Add arm64 as a Build Target

- backends/rapidpro/backend.go
- backends/rapidpro/msg.go
- config.go
- courier.toml
Media is going to be what we call outgoing message media which is managed in the database - attachments are what we call incoming message media.
> Rename S3MediaBucket to S3AttachmentsBucket and S3MediaPrefix to S3AttachmentsPrefix

- handlers/test.go
- handlers/twiml/twiml.go
- handlers/twiml/twiml_test.go
https://app.crisp.chat/website/2a810199-9469-490b-8be9-d3d994c3e788/inbox/session_8864204f-194b-4d8e-9a67-df942106886e/
> Allow twiml channels to send multiple media urls per message

- backends/rapidpro/backend_test.go
- backends/rapidpro/task.go
Going to need these to have mailroom request attachment downloads from courier
> Add channel UUID and type to queued msg events

- attachments.go
- attachments_test.go
- server.go
> Update attachment fetching to handle non-200 response as an unavailable attachment

- backends/rapidpro/backend.go
- backends/rapidpro/contact.go
https://sentry.io/organizations/textit/issues/3745947572/?alert_rule_id=287349&alert_timestamp=1668664879202&alert_type=email&project=205713&referrer=alert_email
> Ensure that URN and contact name are valid utf8 before trying to write to DB

- handlers/facebookapp/facebookapp.go
- handlers/whatsapp/whatsapp.go
- handlers/whatsapp/whatsapp_test.go
Replicates https://github.com/nyaruka/courier/pull/559 for non-cloud WA channels
> Use Msg.locale with on-prem WhatsApp channels too

- handlers/facebookapp/facebookapp.go
- handlers/facebookapp/facebookapp_test.go
> Add support for localizing Menu header on facebook list messages

- handlers/whatsapp/whatsapp.go
- handlers/whatsapp/whatsapp_test.go
> Remove recipient_id requirement on statuses part of WA payload

- handlers/clickatell/clickatell.go
- handlers/generic.go
- handlers/mtn/mtn.go
that takes care of decoding and validaing incoming JSON payloads
> 🧪 Add generic JSON handler wrapper

- handlers/mtn/mtn.go
- handlers/mtn/mtn_test.go
Fixes https://textit.sentry.io/issues/4033744016/
> Address the expired status for MTN msgs

- handlers/hormuud/hormuud.go
- handlers/hormuud/hormuud_test.go
And they're not UNIX timestamps for a start
e.g. https://textit.sentry.io/issues/4104620338/?alert_rule_id=287349&alert_timestamp=1681811949630&alert_type=email&project=205713&referrer=alert_email
> Ignore dates for hormund mo as they're not reliable or accurate

- backends/rapidpro/channel_log.go
- channel_log.go
- channel_log_test.go
- server.go
Requires https://github.com/nyaruka/rapidpro/pull/4631
> Stop writing `ChannelLog.msg`

- backends/rapidpro/backend.go
- backends/rapidpro/backend_test.go
- backends/rapidpro/channel_log.go
- channel_log.go
- channel_log_test.go
- config.go
- server.go
Adds new logs writer which will write attached logs to storage only
> 📜 S3 channel logs

- backends/rapidpro/backend_test.go
- backends/rapidpro/channel.go
- backends/rapidpro/channel_log.go
- backends/rapidpro/schema.sql
- backends/rapidpro/testdata.sql
Which lets us selectively discard channel logs.
Will require changes on RP side to add and backfill that field.
> Add `log_policy` field to channel

- backends/rapidpro/status.go
Removes 1 of the 3 ways to update a message in the db
> Use bulk SQL operation for msg status flushing

- backend.go
- backends/rapidpro/backend.go
- backends/rapidpro/backend_test.go
- backends/rapidpro/task.go
- handlers/facebookapp/facebookapp.go
- test/backend.go
Requires https://github.com/nyaruka/mailroom/pull/113
> Sender deletion handled by mailroom task

- backends/rapidpro/backend.go
- backends/rapidpro/backend_test.go
- backends/rapidpro/status.go
and use for resolving ids for status updates
> Record external ids of sent messages in redis

- backends/rapidpro/backend_test.go
- backends/rapidpro/channel_event.go
- channel_event.go
- handlers/facebook_legacy/handler.go
- handlers/facebook_legacy/handler_test.go
- handlers/meta/facebook_test.go
- handlers/meta/handlers.go
- handlers/meta/instagram_test.go
- handlers/meta/testdata/fba/notification_messages_optin.json
- handlers/meta/testdata/fba/notification_messages_optout.json
- handlers/test.go
- msg.go
- responses.go
- test/channel_event.go
Because if we want a db trigger on contacturn to track counts by optin.. this will make it a lot easier
> Switch to using optin ids instead of uuids

- cmd/courier/main.go
- handlers/forms.go
- handlers/mailgun/handler.go
- handlers/mailgun/handler_test.go
This is working in theory but mailgun is currently sending a payload that I think is incorrectly encoded and am waiting to hear back from their tech support
> Add mailgun handler

- handlers/telegram/handler.go
- handlers/telegram/handler_test.go
- handlers/test.go
- sender.go
- server_test.go
- test/handler.go
...and add support for contact stop events from new sends
> Rework telegram handler to new send method

- handlers/whatsapp_legacy/handler_test.go
No change to the send method as that use status update to update the URN
> Use MockResponses and ExpectedRequests in WA legacy tests

- handlers/twiml/handlers.go
- handlers/twiml/handlers_test.go
matches the attachments for TWA channel as for #752
> Adjust attachment variables for TWA templates

- handlers/firebase/handler.go
So we're not marshalling, unmarshalling, re-marshalling...
> Tidy up getting FCM credentials

- backends/rapidpro/backend_test.go
- backends/rapidpro/channel_log.go
- utils/clogs/dynamo.go
- utils/clogs/dynamo_test.go
Still not sure if this belongs in gocommon, its own repo, or a new repo like "temba-common" that is application logic shared specifically between courier and mailroom.
> Use copy of latest clogs package from mailroom

- attachments.go
https://textit.sentry.io/issues/5497443553
> Ignore `*/*` as an attachment content type

- backends/rapidpro/backend_test.go
- backends/rapidpro/channel_event.go
- backends/rapidpro/task.go
Requires https://github.com/nyaruka/mailroom/pull/443
> Use new ctask names

- handlers/messagebird/handler.go
- handlers/messagebird/handler_test.go
Updated to support Messagebird's default webhook receiving handlers, with both shortcodes and regular numbers.
> Messagebird Handler Updates

- handlers/dialog360/handler.go
- handlers/dialog360/handler_test.go
- handlers/meta/handlers.go
- handlers/meta/whataspp_test.go
- handlers/whatsapp_legacy/handler.go
- handlers/whatsapp_legacy/handler_test.go
- msg.go
Addresses https://github.com/nyaruka/courier/issues/843
Requires https://github.com/nyaruka/mailroom/pull/498
> Support sending quick reply extra as list option description

- handlers/whatsapp_legacy/handler.go
https://textit.sentry.io/issues/6436231842/
> Fix panic from legacy whatsapp handler with bad interactive message payload

- backends/rapidpro/backend.go
- backends/rapidpro/backend_test.go
- backends/rapidpro/channel_log.go
- backends/rapidpro/dynamo.go
- backends/rapidpro/dynamo.json
- utils/clogs/clog.go
- utils/clogs/clog_test.go
Requires https://github.com/nyaruka/rapidpro/pull/6089
> Start writing channel logs to new DynamoDB table

- backends/rapidpro/backend_test.go
- backends/rapidpro/mailroom.go
- go.mod
- go.sum
Requires https://github.com/nyaruka/mailroom/pull/713
> Update to latest vkutil that adds ids to tasks
